[world]
name = "Dojo starter"
description = "The official Dojo Starter guide, the quickest and most streamlined way to get your Dojo Autonomous World up and running. This guide will assist you with the initial setup, from cloning the repository to deploying your world."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "asfad"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"


telegram = "https://t.me/dojoengine"

[namespace]
default = "blockopoly"

[env]
# rpc_url = ""         # env: STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
# world_address = ""

[writers]
"blockopoly" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-GameCounter" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player","blockopoly-property", "blockopoly-trade"]
"blockopoly-Game" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-GamePlayer" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-Player" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]

"blockopoly-UsernameToAddress" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-AddressToUsername" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-IsRegistered" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-IdToProperty" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-PropertyToId" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player","blockopoly-property", "blockopoly-trade"]
"blockopoly-Property" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]

"blockopoly-TradeOfferDetails" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]
"blockopoly-TradeCounter" = ["blockopoly-game", "blockopoly-movement", "blockopoly-player", "blockopoly-property", "blockopoly-trade"]